swagger: '2.0'

basePath: /api

info:
  title: API
  description: API
  version: 1.0.0

paths:
  /:
    get:
      tags:
        - users
      summary: Returns a nice greeting
      description: Returns a nice greeting
      operationId: api.root_get
      responses:
        200:
          description: Successful response.
          schema:
            type: string
            description: Message greeting
            example: Hello!
        500:
          description: Server error
        default:
          description: Unexpected error

  /doc/{doc_id:\d+}:
    post:
      tags: [documents]
      operationId: setDocument
      description: Set document
      parameters:
        - name: doc_id
          in: path
          type: integer
          minimum: 0
        - name: document
          in: body
          schema:
            $ref: 'swagger.yaml#/definitions/Document'
      responses:
        200:
          description: OK
        400:
          description: validation error

definitions:
  Document:
    type: object
    additionalProperties: false
    properties:
      doc_id:
        type: string
      text:
        type: string
    required:
      - text
