version: "3.7"
services:
  rabbit:
    image: itisfoundation/rabbitmq:3.8.0-management
    init: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}    
  
  rabbit-flower:
    # NOTE: latest with DIGEST 9bcc31818a1c7 is broken!
    # SEE https://github.com/mher/flower/issues/1029
    image: mher/flower:0.9.5
    init: true
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}
      - FLOWER_PORT=5555
    ports:
      - "49555:5555"

  redis:
    image: redis:5.0-alpine
    init: true

  redis-commander:
    image: rediscommander/redis-commander:latest
    init: true
    restart: always
    environment:
      - REDIS_HOSTS=${REDIS_HOST}
    ports:
      - "18081:8081"


