Item:
  type: object
  properties:
    id:
      type: string
      format: uuid
    name:
      type: string
      example: my simcore project
    description:
      type: string
      example: a short description of a sample project
    #thumbnail:
    #  type: string
    createdDate:
      type: string
      format: int32
      example: 2019-08-29T09:12:33.001Z
    modifiedDate:
      type: string
      format: int32
      example: 2019-08-29T09:12:33.001Z
Array:
  type: array
  items:
    $ref: '#/ProjectItem'