---
swagger: "2.0"
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /pcrespov/test-simple/1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /projects:
    get:
      summary: searches projects
      parameters:
      - name: searchString
        in: query
        description: pass an options search string to filter project names
        required: false
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/ProjectItem'
        204:
          description: no projects matching search criteria
        400:
          description: requested information is incomplete or malformed
          schema:
            $ref: '#/definitions/Error'
        404:
          description: when everything is okay, but the resource doesn’t exist
          schema:
            $ref: '#/definitions/Error'
        500:
          description: unexpected server error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: adds a new project
      description: Adds an new project to the database
      operationId: addProject
      parameters:
      - in: body
        name: projectItem
        description: Project item to add
        required: false
        schema:
          $ref: '#/definitions/ProjectItem'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/Error'
        409:
          description: a project with the same name already exists
          schema:
            $ref: '#/definitions/Error'
        500:
          description: unexpected server error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ProjectItem:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
        example: my simcore project
      description:
        type: string
        example: a short description of a sample project
      createdDate:
        type: string
        format: int32
        example: 2019-08-29T09:12:33.001Z
      modifiedDate:
        type: string
        format: int32
        example: 2019-08-29T09:12:33.001Z
    example:
      createdDate: 2019-08-29T09:12:33.001Z
      name: my simcore project
      modifiedDate: 2019-08-29T09:12:33.001Z
      description: a short description of a sample project
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
  InventoryItem:
    type: object
    required:
    - id
    - manufacturer
    - name
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: int32
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example: https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
  Error:
    required:
    - code
    - message
    properties:
      code:
        type: integer
        format: int32
        example: 422
      error:
        type: string
        example: FIELDS_VALIDATION_ERROR
      message:
        type: string
        example: One or more request's fields raised validation errors
      fields:
        type: object
        description: a dict with error messages specific fot request's fields
        additionalProperties:
          type: string
