openapi: 3.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/pcrespov/test-simple/1.0.0'
info:
  title: Basic API API
  version: "1.0.0-oas3"
paths:
  /projects:
    get:
      summary: List Project
      operationId: findProjects
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectOutput'
    post:
      summary: Create Project
      operationId: createProject
      responses:
        '201':
          description: ''
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectOutputDetailed'
      requestBody:
        $ref: '#/components/requestBodies/ProjectInput'
  /projects/{projectId}:
    parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get Project
      operationId: getProject
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectOutputDetailed'
    put:
      summary: Update Project
      operationId: updateProject
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectOutputDetailed'
      requestBody:
        $ref: '#/components/requestBodies/ProjectInput'
    delete:
      summary: Delete Project
      operationId: deleteProject
      responses:
        '204':
          description: ''
components:
  schemas:
    ProjectCommon:
      title: Project Common
      description: >-
        The properties that are shared amongst all versions of the Project
        model.
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    ProjectInput:
      title: Project Input
      description: The properties that are allowed when creating or updating a Project.
      allOf:
        - $ref: '#/components/schemas/ProjectCommon'
        - type: object
          properties: {}
    ProjectOutput:
      title: Project Output
      description: The properties that are included when fetching a list of Projects.
      allOf:
        - type: object
          properties:
            thumbnail:
              type: string
              format: uri
            createdOn:
              type: string
              format: date-time
            createdBy:
              type: string
              format: uuid
            projectId:
              type: string
              format: uuid
        - $ref: '#/components/schemas/ProjectCommon'
    ProjectOutputDetailed:
      title: Project Output Detailed
      description: The properties that are included when fetching a single Project.
      allOf:
        - $ref: '#/components/schemas/ProjectOutput'
        - type: object
          properties: {}
  requestBodies:
    ProjectInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectInput'