swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Project API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /pcrespov/test-simple/1.0.0
schemes:
 - https
consumes: 
  - application/json
produces: 
  - application/json
# -------------------  
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
# -------------------    
paths:
  /projects:
    get:
      summary: searches projects
      operationId: listProjects
      parameters:
        - in: query
          name: searchString
          description: pass an options search string to filter project names
          required: false
          type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            $ref: 'models/Project.yml#/Array'
        204:
          description: no projects matching search criteria
        400:
          description: requested information is incomplete or malformed
          schema:          
            $ref: './models/Error.yaml'
        404:
          description: when everything is okay, but the resource doesn’t exist
          schema:
            $ref: 'models/Error.yml'
        500:
          description: unexpected server error
          schema:
            $ref: 'models/Error.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'models/Error.yml'
    post:
      summary: adds a new project
      operationId: addProject
      description: Adds an new project to the database
      parameters:
      - in: body
        name: projectItem
        description: Project item to add
        schema:
          $ref: 'models/Project.yml#/Item'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
          schema:
            $ref: 'models/Error.yml'
        409:
          description: a project with the same name already exists
          schema:
            $ref: 'models/Error.yml'
        500:
          description: unexpected server error
          schema:
            $ref: 'models/Error.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'models/Error.yml'
