version: '3.4'
services:
  # https://hub.docker.com/_/postgres/
  postgres:
    #image: postgres:10-alpine
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: su
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - postgres
volumes:
  pgdata: